name: cubit_example
description: A simple Flutter app that displays 'Cat' with a person icon which changes to 'Dog' with an access time icon on tap.
version: 1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true